### ISSUE TITLE
New menu has some bugs

### ISSUE THREAD

**Issue by piontkowski** [psrm/wp-theme#14]
Menu was added in #13.
@caest100 Can you list the bugs here? I loaded the site on a mac in Chrome and Safari and the menu loads and works fine on all pages. Let me know the devices and browsers and whether it also works on staging.psrm.org.

**Comment by piontkowski** [comment]
Loaded site on latest iOS in safari and the styling was completely gone. The links worked though. Menu looked great and worked as expected on Staging on iOS.

**Comment by mjcaestecker** [comment]
I'm using Windows 8.1 with Chrome.  On pages other than the home page, I see no ability to open the dropdown menus.
![capture1](https://cloud.githubusercontent.com/assets/14098260/16100415/fd5b3a1c-3312-11e6-9184-e6a2dede5353.PNG)

**Comment by mjcaestecker** [comment]
also, styling is gone on Chrome for Android, but the links do function
![screenshot_2016-06-15-16-07-25](https://cloud.githubusercontent.com/assets/14098260/16100455/631b3212-3313-11e6-985f-142481b0a683.png)

**Comment by mjcaestecker** [comment]
I found what was causing the issue.  the data-smartmenus-id inside the ul tag just inside the menu-main-menu-container div was not loading.  However, it now seems to be working.  I tried viewing the page with Chrome's code inspector open, added the smartmenus id into the ul tag and now the issue is not happening on any page I visit.

**Comment by piontkowski** [comment]
@caest100 Try again on your phone and browser. We have the CSS minify plugin running on the production site and I forgot to clear the cache after deploying the new code. I just cleared it. The new menu looks perfect on my phone now.

**Comment by mjcaestecker** [comment]
@piontkowski it works on my computer and my phone now.  That looks realy nice
